name: CI/CD Pipeline AXIOCRM

on:
  push:
    branches: [ main, master ] # Déclenche le pipeline à chaque push sur ces branches

permissions:
  contents: read

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: 1. Récupérer le code du dépôt
      uses: actions/checkout@v4

    - name: 2. Configurer le SDK .NET 8
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: 3. Restaurer les dépendances NuGet
      run: dotnet restore Backend/ProductManager.API.sln

    - name: 4. Compiler l'application complète
      run: dotnet build Backend/ProductManager.API.sln --configuration Release --no-restore

    - name: 5. Exécuter les tests unitaires et d'intégration
      run: dotnet test Backend/ProductManager.API.sln --configuration Release --no-build --verbosity normal

   # Frontend Angular 
  build-and-test-frontend:
    runs-on: ubuntu-latest
    steps:
    - name: 1. Récupérer le code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: 2. Configurer Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: Frontend/package-lock.json

    - name: 3. Installer les dépendances
      working-directory: Frontend
      run: npm ci --legacy-peer-deps

    - name: 4. Build Angular
      working-directory: Frontend
      run: npm run build

    - name: 5. Tests avec coverage
      working-directory: Frontend
      run: npm run test -- --watch=false --code-coverage --browsers=ChromeHeadless

    - name: 6. SonarQube Scan Frontend
      uses: SonarSource/sonarqube-scan-action@master
      with:
        projectBaseDir: Frontend
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}

  build-and-push-docker:
    needs: build-and-test # S'exécute uniquement si les tests passent
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
    - name: 1. Récupérer le code
      uses: actions/checkout@v4

    - name: 2. Connexion automatique à GHCR
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: 3. Build et Push de l'image Docker
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Backend/Dockerfile # Utilise le Dockerfile situé dans le dossier Backend
        push: true
        tags: ghcr.io/oumaima-benabdallah/axiocrm-backend:latest