name: Frontend CI

on:
  push:
    branches: [ main, master, develop ]
  pull_request:
    branches: [ main, master ]

jobs:
  build-and-sonar:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout du code
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # important pour SonarQube

      # 2. Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: Frontend/package-lock.json

      # 3. Installer les dépendances
      - name: Install dependencies
        working-directory: Frontend
        run: npm ci

      # 4. Build
      - name: Build
        working-directory: Frontend
        run: npm run build --prod

      # 5. Tests + Coverage pour SonarQube
      - name: Test with coverage
        working-directory: Frontend
        run: npm run test -- --watch=false --code-coverage --browsers=ChromeHeadless

      # 6. SonarQube Scan
      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@master
        with:
          projectBaseDir: Frontend
        env:
          SONAR_TOKEN: ${{ c865d530d272dfb39cfd951543d8e0525c72ca63 }}
          SONAR_HOST_URL: ${{ http://localhost:9000 }}